name: iOS CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Show Xcode Version
        run: xcodebuild -version
        
      - name: List Simulators
        run: xcrun simctl list devices
        
      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies

      - name: Build Application
        run: xcodebuild clean build \
            -scheme QuoteApp \
            -destination 'generic/platform=iOS Simulator'
    
