name: iOS CI

on:
   push:
     branches:
      -main
      -develop
      
   pull_request:
       -main
       -develop
 jobs:
    build-and-test:
    runs-on: macos-latest
    
    steps:
     -name: Checkout Code
     users: action/checkout@4
     
     -name: Select xcode
      run:  sudo xcode-Select -switch /Applications/Xcode.Applications
         
    -name: show Xcdoe version
     run: xcodebuild -version
     
    -name: Resolve Swift packages
        run : xcodebuild -resovePackageDependencies
        
    -name: Build Applications
        run : xcodebuild clean build \
              -scheme QuoteApp \
              -destination 'platform=iOS Simulator,name=iPhone 15'\
              CODE_SIGNIG_ALLOWED=NO
    
       
